### ISSUE TITLE
tabbar切换失灵

### ISSUE THREAD

**Issue by antybody** [zjhr/vue-amazeui#1]
在href 和 active 同时存在，切换标签，active  已经高亮了，但是没触发 href ，导致内容框和地址栏都无变化
 出现这个状态，有个特定的情况下，鼠标没有点击在图标或者文字上，而是在距离一段触发点击事件后高亮了，href无变化 @zjhr 
![image](https://user-images.githubusercontent.com/16040676/34510550-b45dd54a-f08f-11e7-9757-da7f43999081.png)

**Comment by antybody** [comment]
![image](https://user-images.githubusercontent.com/16040676/34510547-a48d0f1e-f08f-11e7-9713-74570f866a06.png)

**Comment by zjhr** [comment]
你好，目前不维护了，请不要使用在项目上，随着手机系统，浏览器的更新，是会存在一些bug，可以把工程里面的css换成最新版的react那个Amaze UI Touch的css重新打包尝试一下，这样应该可以避免一些bug，https://github.com/amazeui/amazeui-touch/tree/master/dist

**Comment by antybody** [comment]
嗯，嗯，fork 了一个 自己改改，感谢作者前期提供的轮子~~
